### ISSUE TITLE
v1.3.2 exe file not working (v1.3.0 did, befure 11.5 update)

### ISSUE THREAD

**Issue by NGD-Skier** [nicolas-f/7DTD-leaflet#13]
Issue originally noted this issue here:
https://7daystodie.com/forums/showthread.php?14947-Export-discovered-map-to-png/page9

But I thought I'd post it here to make it more "official"  :-)

  -Skier

[error message]
C:\Scripts\7DTD>Update_7DTD_Map.bat
WARNING: file already exists but should not: C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI13882\include\pyconfig.h
Welcome to 7DTD leflet builder version 1.3.2
This program require:
Pillow https://pillow.readthedocs.org/en/latest/

Traceback (most recent call last):
  File "<string>", line 39, in <module>
NameError: name 'exit' is not defined
[/error message]

It gets to the "Pillow" line, then stops there...  If I then hit enter, it gives the rest of the text above, and exits.

I looked in the temp directory it references, and I deleted that directory and tried again, but I get the same results.

  -Skier[/QUOTE]

**Comment by nicolas-f** [comment]
Hi,

Thank you for report. I  don't know for the pyconfig.h. But the dependency has been fixed and the exe pushed again.

**Comment by NGD-Skier** [comment]
It's working now.  I still get the pyconfig.h warning, but it does work now.  :-)  I'll paste the output from my run below.

  -Skier

WARNING: file already exists but should not: C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI39842\include\pyconfig.h
Welcome to 7DTD leflet builder version 1.3.3-dev
Store all version of tiles, may take huge disk space
Read map file  76561198004007366.map 1 / 10
Read map file  76561198044199615.map 2 / 10
Read map file  76561198177348699.map 3 / 10
Read map file  76561197994896524.map 4 / 10
Read map file  76561197987915877.map 5 / 10
Read map file  76561198051634732.map 6 / 10
Read map file  76561197964869044.map 7 / 10
Read map file  76561197990266641.map 8 / 10
Warning old map version:  2377473
Read map file  76561198069207996.map 9 / 10
Warning old map version:  1401345
Warning old map version:  415233
Write tile X: 1  of  256
Write tile X: 5  of  256
Write tile X: 10  of  256
Write tile X: 14  of  256
Write tile X: 19  of  256
Write tile X: 24  of  256
Write tile X: 29  of  256
Write tile X: 33  of  256
Write tile X: 37  of  256
Write tile X: 42  of  256
Write tile X: 46  of  256
Write tile X: 49  of  256
Write tile X: 50  of  256
Write tile X: 51  of  256
Write tile X: 52  of  256
Write tile X: 53  of  256
Write tile X: 55  of  256
Write tile X: 58  of  256
Write tile X: 61  of  256
Write tile X: 64  of  256
Write tile X: 67  of  256
Write tile X: 69  of  256
Write tile X: 70  of  256
Write tile X: 71  of  256
Write tile X: 72  of  256
Write tile X: 73  of  256
Write tile X: 74  of  256
Write tile X: 75  of  256
Write tile X: 76  of  256
Write tile X: 77  of  256
Write tile X: 78  of  256
Write tile X: 79  of  256
Write tile X: 80  of  256
Write tile X: 81  of  256
Write tile X: 82  of  256
Write tile X: 83  of  256
Write tile X: 84  of  256
Write tile X: 85  of  256
Write tile X: 86  of  256
Write tile X: 87  of  256
Write tile X: 88  of  256
Write tile X: 89  of  256
Write tile X: 90  of  256
Write tile X: 91  of  256
Write tile X: 92  of  256
Write tile X: 93  of  256
Write tile X: 95  of  256
Write tile X: 97  of  256
Write tile X: 98  of  256
Write tile X: 99  of  256
Write tile X: 100  of  256
Write tile X: 102  of  256
Write tile X: 103  of  256
Write tile X: 104  of  256
Write tile X: 105  of  256
Write tile X: 106  of  256
Write tile X: 107  of  256
Write tile X: 108  of  256
Write tile X: 109  of  256
Write tile X: 110  of  256
Write tile X: 112  of  256
Write tile X: 114  of  256
Write tile X: 115  of  256
Write tile X: 117  of  256
Write tile X: 119  of  256
Write tile X: 121  of  256
Write tile X: 123  of  256
Write tile X: 125  of  256
Write tile X: 127  of  256
Write tile X: 128  of  256
Write tile X: 129  of  256
Write tile X: 130  of  256
Write tile X: 131  of  256
Write tile X: 132  of  256
Write tile X: 133  of  256
Write tile X: 134  of  256
Write tile X: 135  of  256
Write tile X: 136  of  256
Write tile X: 137  of  256
Write tile X: 138  of  256
Write tile X: 139  of  256
Write tile X: 140  of  256
Write tile X: 141  of  256
Write tile X: 142  of  256
Write tile X: 143  of  256
Write tile X: 144  of  256
Write tile X: 145  of  256
Write tile X: 146  of  256
Write tile X: 147  of  256
Write tile X: 148  of  256
Write tile X: 149  of  256
Write tile X: 150  of  256
Write tile X: 151  of  256
Write tile X: 152  of  256
Write tile X: 153  of  256
Write tile X: 154  of  256
Write tile X: 155  of  256
Write tile X: 156  of  256
Write tile X: 157  of  256
Write tile X: 158  of  256
Write tile X: 159  of  256
Write tile X: 160  of  256
Write tile X: 161  of  256
Write tile X: 162  of  256
Write tile X: 163  of  256
Write tile X: 164  of  256
Write tile X: 165  of  256
Write tile X: 166  of  256
Write tile X: 167  of  256
Write tile X: 168  of  256
Write tile X: 169  of  256
Write tile X: 170  of  256
Write tile X: 171  of  256
Write tile X: 172  of  256
Write tile X: 173  of  256
Write tile X: 174  of  256
Write tile X: 175  of  256
Write tile X: 176  of  256
Write tile X: 177  of  256
Write tile X: 178  of  256
Write tile X: 179  of  256
Write tile X: 180  of  256
Write tile X: 181  of  256
Write tile X: 182  of  256
Write tile X: 183  of  256
Write tile X: 184  of  256
Write tile X: 185  of  256
Write tile X: 186  of  256
Write tile X: 189  of  256
Write tile X: 194  of  256
Write tile X: 199  of  256
Write tile X: 205  of  256
Write tile X: 210  of  256
Write tile X: 215  of  256
Write tile X: 220  of  256
Write tile X: 224  of  256
Write tile X: 228  of  256
Write tile X: 232  of  256
Write tile X: 237  of  256
Write tile X: 242  of  256
Write tile X: 248  of  256
Write tile X: 253  of  256
Min max tiles minx: -1309  maxx: 923 miny: -899  maxy:  1347
Tiles used / total read 211179  /  63471
Zoom level  7 ,  1731  tiles left
Zoom level  7 ,  1703  tiles left
Zoom level  7 ,  1665  tiles left
Zoom level  7 ,  1633  tiles left
Zoom level  7 ,  1602  tiles left
Zoom level  7 ,  1569  tiles left
Zoom level  7 ,  1519  tiles left
Zoom level  7 ,  1475  tiles left
Zoom level  7 ,  1431  tiles left
Zoom level  7 ,  1388  tiles left
Zoom level  7 ,  1352  tiles left
Zoom level  7 ,  1310  tiles left
Zoom level  7 ,  1258  tiles left
Zoom level  7 ,  1221  tiles left
Zoom level  7 ,  1182  tiles left
Zoom level  7 ,  1145  tiles left
Zoom level  7 ,  1100  tiles left
Zoom level  7 ,  1059  tiles left
Zoom level  7 ,  1018  tiles left
Zoom level  7 ,  976  tiles left
Zoom level  7 ,  933  tiles left
Zoom level  7 ,  882  tiles left
Zoom level  7 ,  835  tiles left
Zoom level  7 ,  803  tiles left
Zoom level  7 ,  769  tiles left
Zoom level  7 ,  728  tiles left
Zoom level  7 ,  679  tiles left
Zoom level  7 ,  629  tiles left
Zoom level  7 ,  590  tiles left
Zoom level  7 ,  552  tiles left
Zoom level  7 ,  509  tiles left
Zoom level  7 ,  460  tiles left
Zoom level  7 ,  428  tiles left
Zoom level  7 ,  379  tiles left
Zoom level  7 ,  335  tiles left
Zoom level  7 ,  281  tiles left
Zoom level  7 ,  230  tiles left
Zoom level  7 ,  181  tiles left
Zoom level  7 ,  141  tiles left
Zoom level  7 ,  95  tiles left
Zoom level  7 ,  57  tiles left
Zoom level  7 ,  37  tiles left
Zoom level  7 ,  9  tiles left
Zoom level  6 ,  594  tiles left
Zoom level  6 ,  556  tiles left
Zoom level  6 ,  515  tiles left
Zoom level  6 ,  481  tiles left
Zoom level  6 ,  437  tiles left
Zoom level  6 ,  384  tiles left
Zoom level  6 ,  346  tiles left
Zoom level  6 ,  308  tiles left
Zoom level  6 ,  254  tiles left
Zoom level  6 ,  203  tiles left
Zoom level  6 ,  159  tiles left
Zoom level  6 ,  115  tiles left
Zoom level  6 ,  78  tiles left
Zoom level  6 ,  38  tiles left
Zoom level  6 ,  16  tiles left
Zoom level  5 ,  218  tiles left
Zoom level  5 ,  176  tiles left
Zoom level  5 ,  122  tiles left
Zoom level  5 ,  68  tiles left
Zoom level  5 ,  39  tiles left
Zoom level  4 ,  82  tiles left
Zoom level  4 ,  32  tiles left
Zoom level  3 ,  28  tiles left
Zoom level  1 ,  4  tiles left

In case you're curious, the contents of my bat file are as follows:

@echo off
c:
cd c:\inetpub\wwwroot\7DTDMap\
C:\inetpub\wwwroot\7DTDMap\map_reader1.3.2_64bits.exe -n -g "C:\Users\Administrator\Documents\7 Days To Die\Saves\Random Gen\NGD 7DTD Random Gen 01\Player"
cd C:\Scripts\7DTD\

Come to think of it, I shouldn't be running my server out of my admin account...  I'll have to fix that.   :-)

I'll just do this as a comment (instead of close and comment), and you can decide if we should close it and ignore the warning I get, leave it open because of that warning, or open a separate ticket for the warning.  Let me know, and thanks for the fix!

**Comment by nicolas-f** [comment]
Its an issue of PyInstaller. I have to wait for an update on their side..
https://github.com/pyinstaller/pyinstaller/issues/782
